#!/bin/sh
set -eu

BEACON_BIN="${BEACON_BIN:-/opt/beacon/bin/beacon}"
BEACON_COLLECTOR="${BEACON_COLLECTOR:-${4:-/opt/beacon/bin/beacon-otelcol}}"
BEACON_INSTALL_SCRIPT="${BEACON_INSTALL_SCRIPT:-/opt/beacon/scripts/install-endpoint.sh}"

BEACON_BIN="$BEACON_BIN" \
BEACON_ENDPOINT_HARNESSES="${BEACON_ENDPOINT_HARNESSES:-${1:-claude,codex}}" \
BEACON_OTLP_GRPC_PORT="${BEACON_OTLP_GRPC_PORT:-${2:-4317}}" \
BEACON_OTLP_HTTP_PORT="${BEACON_OTLP_HTTP_PORT:-${3:-4318}}" \
BEACON_COLLECTOR="$BEACON_COLLECTOR" \
BEACON_NO_START="${BEACON_NO_START:-${5:-0}}" \
BEACON_SPLUNK_HEC_ENDPOINT="${BEACON_SPLUNK_HEC_ENDPOINT:-${6:-}}" \
BEACON_SPLUNK_HEC_TOKEN="${BEACON_SPLUNK_HEC_TOKEN:-${7:-}}" \
BEACON_SPLUNK_INDEX="${BEACON_SPLUNK_INDEX:-${8:-}}" \
BEACON_SPLUNK_SOURCE="${BEACON_SPLUNK_SOURCE:-${9:-}}" \
BEACON_SPLUNK_SOURCETYPE="${BEACON_SPLUNK_SOURCETYPE:-${10:-}}" \
BEACON_SPLUNK_INSECURE_SKIP_VERIFY="${BEACON_SPLUNK_INSECURE_SKIP_VERIFY:-${11:-0}}" \
BEACON_SPLUNK_CA_FILE="${BEACON_SPLUNK_CA_FILE:-${12:-}}" \
BEACON_FALCON_HEC_ENDPOINT="${BEACON_FALCON_HEC_ENDPOINT:-}" \
BEACON_FALCON_HEC_TOKEN="${BEACON_FALCON_HEC_TOKEN:-}" \
BEACON_FALCON_INDEX="${BEACON_FALCON_INDEX:-}" \
BEACON_FALCON_SOURCE="${BEACON_FALCON_SOURCE:-}" \
BEACON_FALCON_SOURCETYPE="${BEACON_FALCON_SOURCETYPE:-}" \
BEACON_FALCON_INSECURE_SKIP_VERIFY="${BEACON_FALCON_INSECURE_SKIP_VERIFY:-0}" \
BEACON_FALCON_CA_FILE="${BEACON_FALCON_CA_FILE:-}" \
  "$BEACON_INSTALL_SCRIPT"
