#!/bin/sh
set -eu

BEACON_BIN="${BEACON_BIN:-/opt/beacon/bin/beacon}"
BEACON_COLLECTOR="${BEACON_COLLECTOR:-${5:-/opt/beacon/bin/beacon-otelcol}}"
BEACON_INSTALL_SCRIPT="${BEACON_INSTALL_SCRIPT:-/opt/beacon/scripts/install-endpoint.sh}"

BEACON_BIN="$BEACON_BIN" \
BEACON_ENDPOINT_HARNESSES="${BEACON_ENDPOINT_HARNESSES:-${1:-claude,codex}}" \
BEACON_CONTENT_RETENTION="${BEACON_CONTENT_RETENTION:-${2:-full}}" \
BEACON_OTLP_GRPC_PORT="${BEACON_OTLP_GRPC_PORT:-${3:-4317}}" \
BEACON_OTLP_HTTP_PORT="${BEACON_OTLP_HTTP_PORT:-${4:-4318}}" \
BEACON_COLLECTOR="$BEACON_COLLECTOR" \
BEACON_NO_START="${BEACON_NO_START:-${6:-0}}" \
BEACON_SPLUNK_HEC_ENDPOINT="${BEACON_SPLUNK_HEC_ENDPOINT:-${7:-}}" \
BEACON_SPLUNK_HEC_TOKEN="${BEACON_SPLUNK_HEC_TOKEN:-${8:-}}" \
BEACON_SPLUNK_INDEX="${BEACON_SPLUNK_INDEX:-${9:-}}" \
BEACON_SPLUNK_SOURCE="${BEACON_SPLUNK_SOURCE:-${10:-}}" \
BEACON_SPLUNK_SOURCETYPE="${BEACON_SPLUNK_SOURCETYPE:-${11:-}}" \
BEACON_SPLUNK_INSECURE_SKIP_VERIFY="${BEACON_SPLUNK_INSECURE_SKIP_VERIFY:-${12:-0}}" \
BEACON_SPLUNK_CA_FILE="${BEACON_SPLUNK_CA_FILE:-${13:-}}" \
  "$BEACON_INSTALL_SCRIPT"
